### ISSUE TITLE
feature/parallel_computing_fitness_functions

### ISSUE THREAD

**Issue by VictorPelaez** [VictorPelaez/coral-reef-optimization-algorithm#48]
Parallelize fitness computation

```
    def fitness(self, REEFpob):
 
        REEF_fitness = Parallel(n_jobs=1)(delayed(self.fitness_coral)(coral) for coral in REEFpob)
        return self.opt_multiplier*np.array(REEF_fitness)
```

**Comment by VictorPelaez** [comment]
another aproach:

```
import time
from multiprocessing import Pool
import numpy as np

def max_ones(coral):
    return 100*(sum(coral) / len(coral))

if __name__ == '__main__':
    
    REEFpob = np.ones([100000, 1000])
    
    start = time.time()
    result = [max_ones(coral) for coral in REEFpob]
    print ('Singled threaded', time.time() - start, 'seconds')
    
    start = time.time()
    p = Pool(processes = 4)         
    result = p.map(max_ones, [coral for coral in REEFpob])
    #print(p.map(max_ones, [coral for coral in REEFpob]))         
    p.close()
    p.join()
    print ('Pool', time.time() - start, 'seconds')  
```

**Comment by apastors** [comment]
I tried both options, and I get basically the same error, that happens when we use `lambda` functions.
Below you can see the traceback when using the first approach:
```
Traceback (most recent call last):
  File "example_advanced.py", line 55, in <module>
    cro = CRO(Ngen, N, M, Fb, Fa, Fd, r0, k, Pd, fitness_coral, opt, L, seed=13, verbose=True)
  File "/home/alvaro/proyects/cro/cro/cro.py", line 34, in __init__
    self.fitness_coral = delayed(fitness_coral)
  File "/home/alvaro/venvs/cro3/lib/python3.5/site-packages/joblib/parallel.py", line 183, in delayed
    pickle.dumps(function)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7f3d02fe4f28>: attribute lookup <lambda> on __main__ failed
```
So I can see two options:
 1) We implement the function with low level tools: harder but hopefully we will be able to use `lambda`s
 2) We avoid and forbid using `lambda` functions: A bit annoying as `lambda`s are so compact.

**Comment by apastors** [comment]
I found a nice solution using the [multiprocess](https://pypi.python.org/pypi/multiprocess) package.
Below you can find a comparison in results and timing when using 8 processes.

`examples_basic.py`
Develop branch:
```
Best coral:  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Best solution:  100.0
Example I: max_ones problem 0.6928517818450928 seconds.
Best coral:  [10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]
Best solution:  1000.0
Example II: max problem in a discrete interval 1.5562083721160889 seconds.
```
Parallel fitness computation branch:
```
Best coral:  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
Best solution:  100.0
Example I: max_ones problem 2.470712184906006 seconds.
Best coral:  [10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10]
Best solution:  1000.0
Example II: max problem in a discrete interval 4.048856735229492 seconds.
```

`examples_advanced.py`
Develop branch:
```
Best coral:  [0 0 0 1 0 1 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
Best solution:  0.98179427934
Example I: feature selection Classification (max auc):  25.784558057785034 seconds.
['Q25' 'IQR' 'skew' 'centroid' 'meanfun' 'maxfun' 'mindom']
Best coral:  [1 0 1 1 1 1 0 1 1 1 1 0 1]
Best solution:  2.71624290491
Example II: feature selection, regression (min mse):  93.18305206298828 seconds.
['CRIM' 'INDUS' 'CHAS' 'NOX' 'RM' 'DIS' 'RAD' 'TAX' 'PTRATIO' 'LSTAT']
```
Parallel fitness computation branch:
```
Best coral:  [1 1 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
Best solution:  0.992992514732
Example I: feature selection Classification (max auc):  13.978983402252197 seconds.
['meanfreq' 'sd' 'Q25' 'IQR' 'meanfun' 'maxfun' 'modindx']
Best coral:  [0 1 1 0 1 1 0 0 1 1 0 0 1]
Best solution:  2.79228622596
Example II: feature selection, regression (min mse):  36.2103374004364 seconds.
['ZN' 'INDUS' 'NOX' 'RM' 'RAD' 'TAX' 'LSTAT']
```

When the computation time of the fitness function is small, using multiprocessing is actually worse, but when takes long, the speed-up is considerable (between 2x-3x in this specific case).
Also note that the results are not the same anymore, I think it is because of the random seed

**Comment by apastors** [comment]
I still have some issues when executing the code with python2, but due to the plotting, not the actual computation. I will push the code as soon as I solve that.

**Comment by VictorPelaez** [comment]
@apastors  it looks nice! 
Results are not the same anymore? it doesn't make sense, doesn't it? but, are they the same in each execution?

**Comment by apastors** [comment]
Yes, I would say it's due to the random seed.
https://github.com/VictorPelaez/coral-reef-optimization-algorithm/blob/c0dfe265a391b01c7c664eded45f28e7dfd6732c/cro/fitness.py#L47
As now the each process starts when possible, it can be that results differ slightly. Does this make sense? I think so, right?
