### ISSUE TITLE
Uses, but does not have a dependency on, multiprocessing

### ISSUE THREAD

**Issue by musicinmybrain** [VictorPelaez/coral-reef-optimization-algorithm#73]
**Expected behaviour:**

The package declares all its dependencies.

**Actual behaviour:**

The package imports from [`multiprocess`](https://pypi.org/project/multiprocess/), but does not have a dependency on it in `setup.py`.

https://github.com/VictorPelaez/coral-reef-optimization-algorithm/blob/406d7b52c1c1ec61a0fb37a4e27645b618442bda/cro/cro.py#L7

---
 - Python version[s]: 3.11, but this is irrelevant.

Do not forget to label the issue properly and asign it to a milestone if necessary 

---

I suspect you intended to use the [`multiprocessing`](https://docs.python.org/3/library/multiprocessing.html) module from the standard library, which does offer `Pool` and `cpu_count`. If that is the case, the fix is to change the import. If you really needed the third-party fork `multiprocess`, then it should be added to `setup.py`.

**Comment by musicinmybrain** [comment]
Hmm... it looks like you really do need `multiprocess` for the “enhanced serialization.”

```
+ /usr/bin/python3 examples/example_advanced.py
Using bin_binary for initializing the reef
Using bin_larvaemutation for the brooding operator
Running Initialization: max
Traceback (most recent call last):
  File "/builddir/build/BUILD/cro-0.0.5.2/examples/example_advanced.py", line 56, in <module>
    (REEF, REEFpob, REEFfitness, ind_best, Bestfitness, Meanfitness) = cro.fit(X, y, clf)
                                                                       ^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/cro-0.0.5.2/cro/cro.py", line 337, in fit
    REEFfitness = self.fitness(REEFpob)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/cro-0.0.5.2/cro/cro.py", line 75, in fitness
    REEF_fitness = p.map(self.fitness_coral, REEFpob)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib64/python3.12/multiprocessing/pool.py", line 540, in _handle_tasks 
    put(task)
  File "/usr/lib64/python3.12/multiprocessing/connection.py", line 205, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7f02ac339080>: attribute lookup <lambda> on __main__ failed
```

I will open a PR.
